[build]
  publish = "packages/gatsby-ucla-site/public"
  command = "yarn workspace gatsby-ucla-site build"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.10"
  YARN_FLAGS = "--no-ignore-optional"