backend:
  name: github
  repo: Hyperobjekt/covid-19-behind-bars
  branch: staging

# FOR LOCAL DEVELOPMENT:
# ---
# - uncomment the backend below
# - run `npx netlify-cms-proxy-server` to serve content

# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: main # optional, defaults to master

media_folder: /packages/gatsby-ucla-site/content/assets
public_folder: /packages/gatsby-ucla-site/assets

collections:
  - label: "Subsidiary Pages"
    name: "pages"
    extension: mdx
    format: frontmatter
    create: true
    filter: {field: "is_home", value: false}
    folder: "/packages/gatsby-ucla-site/content/pages"
    editor:
      preview: false
    fields:
      - {
          label: "Page Title",
          name: title,
          widget: string,
          hint: "Title for the browser window",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
          hint: "Not visible, but used for search engine optimization",
        }
      - {
          label: "Is Home",
          name: "is_home",
          widget: hidden,
          required: false,
          default: false,
      }  
      - { label: "Keywords", name: "keywords", widget: "list", required: false }
      - {
          label: "Social Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Image used when page is shared on social media",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Home Page"
    name: "homepage"
    extension: mdx
    format: frontmatter
    create: true
    filter: {field: "is_home", value: true}
    folder: "/packages/gatsby-ucla-site/content/pages"
    editor:
      preview: false
    fields:
      - {
          label: "Page Title",
          name: title,
          widget: string,
          hint: "Title for the browser window",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
          hint: "Not visible, but used for search engine optimization",
        }
      - {
          label: "Is Home",
          name: "is_home",
          widget: hidden,
          required: false,
          default: false,
      }  
      - { label: "Keywords", name: "keywords", widget: "list", required: false }
      - { label: "Template", name: "template", widget: hidden }
      - { label: "Path", name: "path", widget: hidden }
      - {
          label: "Social Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Image used when page is shared on social media",
        }
      - { label: "Body", name: "body", widget: "markdown" }    
