backend:
  name: git-gateway
  repo: Hyperobjekt/covid-19-behind-bars
  branch: feature/blog-3 # TODO: update

publish_mode: editorial_workflow  

# FOR LOCAL DEVELOPMENT:
# ---
# - uncomment the backend below
# - run `npx netlify-cms-proxy-server` to serve content

# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: cms # optional, defaults to master

media_folder: /packages/gatsby-ucla-site/content/assets
public_folder: /packages/gatsby-ucla-site/assets

collections:
  - label: "Subsidiary Pages"
    name: "pages"
    extension: mdx
    format: frontmatter
    create: true
    filter: {field: "pagetype", value: "subsidiary"}
    folder: "/packages/gatsby-ucla-site/content/pages"
    editor:
      preview: false
    fields:
      - {
          label: "Page Title",
          name: title,
          widget: string,
          hint: "Title for the browser window",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
          hint: "Not visible, but used for search engine optimization",
        }
      - {
          label: "Page Type",
          name: "pagetype",
          widget: hidden,
          required: false,
          default: "subsidiary",
      }  
      - { label: "Keywords", name: "keywords", widget: "list", required: false }
      - {
          label: "Social Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Image used when page is shared on social media",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Home Page"
    name: "homepage"
    extension: mdx
    format: frontmatter
    create: true
    folder: "/packages/gatsby-ucla-site/content/pages"
    editor:
      preview: false
    filter: {field: "pagetype", value: "home" }  
    fields:
      - {
          label: "Page Title",
          name: title,
          widget: string,
          hint: "Title for the browser window",
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
          hint: "Not visible, but used for search engine optimization",
        }
      - {
          label: "Page Type",
          name: "pagetype",
          widget: hidden,
          required: false,
          default: "home",
        }  
      - { label: "Keywords", name: "keywords", widget: "list", required: false }
      - { label: "Template", name: "template", widget: hidden }
      - { label: "Path", name: "path", widget: hidden }
      - {
          label: "Social Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Image used when page is shared on social media",
        }
      - label: "Intro"
        name: intro
        widget: object
        required: false
        fields: 
          - {label: Title, name: title, widget: string, required: false}
          - {label: Subtitle, name: subtitle, widget: string, required: false} 
          - {label: Body, name: body, widget: markdown, required: false}
      - label: "Table notes"
        name: table
        widget: object
        required: false
        fields: 
          - {label: Notes, name: note, widget: markdown, required: false}
      - label: "Sponsors"
        name: sponsors
        widget: object
        required: false
        fields: 
          - {label: Title, name: title, widget: markdown, required: false}    
          - name: "blog"
  - label: "Blog post"
    folder: "/packages/gatsby-ucla-site/content/pages/blog"
    name: "blogpost"
    extension: mdx
    format: frontmatter
    create: true
    
    # slug: "blogPost"
    media_folder: ""
    public_folder: ""
    path: "{{title}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
        label: "Slug",
        name: "path",
        widget: "string",
        default: "blog/",
        hint: "Sets the link to the post. Must be unique, begin with 'blog/', and be composed only of alphanumeric characters and dashes",
        required: true,
        pattern: [
          "^blog/[a-z0-9]+(?:-[a-z0-9]+)*$",
          "A slug must begin with 'blog/' can have no spaces or special characters, e.g. 'blog/why-we-built-this'"
        ]
        }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, hint: "Whether to display as the featured post on the blog index page. If more than one post is marked as featured, the most recent one will be used." }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Post Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Image to embed in post",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Is Post", name: "isBlogPost", widget: "hidden", default: true }
      - { label: "Template", name: "template", widget: "hidden", default: "blog" }



   
